GET http://localhost:8080/list?limit=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQHRlc3Qub3JnIiwiaWF0IjoxNzMzNTgxMDI3LCJleHAiOjE3MzM1ODQ2Mjd9.VS_80MBtLZN1xGubHj6oKY_t4B6eC-chrC-sKqmTvDVglCJuhMZlrBQ603nLEBsStH_3TdGCY_P207IYei9xgA